# Code for preprocessing CRCNS fcx-1 dataset

In [1]:
import numpy as np
from scipy import io
import os
import pandas as pd

In [2]:
basepath = '/Users/rdgao/Documents/data/CRCNS/fcx1/'
rec_dirs = [f for f in np.sort(os.listdir(basepath)) if os.path.isdir(basepath+f)]

# Reorganizing behavioral data into dataframe and save out as csv

In [247]:
for cur_rec in range(len(rec_dirs)):
    print(rec_dirs[cur_rec])
    wakesleep = io.loadmat(basepath+rec_dirs[cur_rec]+'/'+rec_dirs[cur_rec]+'_WSRestrictedIntervals.mat', squeeze_me=True)
    df_wakesleep = pd.DataFrame()
    for k in wakesleep.keys():
        # grab only the timepair matrices
        if 'TimePair' in k:
            # make sure it's not empty
            if wakesleep[k].shape[0]:
                if 'WakeSleep' in k:
                    if len(wakesleep[k].shape)==1:
                        # multiple WS periods, array of arrays
                        df_cur = pd.DataFrame([np.append(block[0,:],block[1,1]) for block in wakesleep['WakeSleepTimePairFormat']], columns=['Start', 'Inter', 'End'])
                    else:
                        # single WS period, 2x2 array
                        block = wakesleep[k]
                        df_cur = pd.DataFrame([np.append(block[0,:],block[1,1])], columns=['Start', 'Inter', 'End'])
                    df_cur.insert(0,'Label',[k[:-14]]*df_cur.shape[0])
                else:
                    # manually deal with 1-D array because pandas will assume array to be columns
                    data_block = [wakesleep[k]] if len(wakesleep[k].shape)==1 else wakesleep[k]
                    df_cur = pd.DataFrame(data_block, columns=['Start', 'End'])
                    df_cur.insert(0,'Label',[k[:-14]]*df_cur.shape[0])
                # append to overall segment
                df_wakesleep = df_wakesleep.append(df_cur, ignore_index=True)
    # rearrange labels
    df_wakesleep = df_wakesleep[['Label','Start','Inter','End']]
    # save to disk
    df_wakesleep.to_csv(basepath+rec_dirs[cur_rec]+'/'+rec_dirs[cur_rec]+'_wakesleep.csv')

20140526_277um
20140527_421um
20140528_565um
BWRat17_121712
BWRat17_121912
BWRat18_020513
BWRat19_032413
BWRat19_032513
BWRat20_101013
BWRat20_101513
BWRat21_121113
BWRat21_121613
BWRat21_121813
Bogey_012615
Dino_061814_mPFC
Dino_061914_ACC
Dino_061914_mPFC
Dino_062014_ACC
Dino_062014_mPFC
Dino_072114_mPFC
Dino_072314_mPFC
Dino_072414_mPFC
Rizzo_022615
Rizzo_022715
Splinter_020515
Splinter_020915
Templeton_032415

In [258]:
cur_rec=0
data = io.loadmat(basepath+rec_dirs[cur_rec]+'/'+rec_dirs[cur_rec]+'_combined.mat', squeeze_me=True)
pd.DataFrame(data['spike_info'], columns=data['spike_info_cols'])

    cell_id  shank  cell_EI_type  num_spikes  num_spikes_cumsum
0         1      1             1        5209               5209
1         2      1             1        5450              10659
2         3      1             1        9648              20307
3         4      1             1        9109              29416
4         5      1             1       10688              40104
5         6      1             1       20261              60365
6         7      1             1       37509              97874
7         8      1             1       19808             117682
8         9      1            -1      129273             246955
9        10      1             1       35203             282158
10       11      1             1       62425             344583
11       12      1             1       41202             385785
12       13      1            -1        4310             390095
13       14      1            -1       54034             444129
14       15      1             1       11953             456082
15       16      1             1        9046             465128
16       17      1             1       21441             486569
17       18      2             1       19967             506536
18       19      2             1       27110             533646
19       20      2             1        6491             540137
20       21      2            -1       83629             623766
21       22      2             1       10575             634341
22       23      2             1       24318             658659
23       24      2             1        3452             662111
24       25      2             1        5401             667512
25       26      2             1        3924             671436
26       27      2             1        8210             679646
27       28      2             1        7061             686707
28       29      3             1        6248             692955
29       30      3             1       18835             711790
..      ...    ...           ...         ...                ...
32       33      3             1       22903             885710
33       34      3             1        8020             893730
34       35      3            -1      139410            1033140
35       36      3             1       16173            1049313
36       37      3             1       19327            1068640
37       38      3             1       27274            1095914
38       39      3             1       12000            1107914
39       40      3             1       16885            1124799
40       41      3            -1       49921            1174720
41       42      3             1        7983            1182703
42       43      3             1       29389            1212092
43       44      3             1       29400            1241492
44       45      3             1       16539            1258031
45       46      4             1        6071            1264102
46       47      4             1       13719            1277821
47       48      4             1       32380            1310201
48       49      4             1        5406            1315607
49       50      4             1       26113            1341720
50       51      4             1       27191            1368911
51       52      4             1        2214            1371125
52       53      4            -1      244432            1615557
53       54      4             1        4449            1620006
54       55      4            -1       87564            1707570
55       56      4            -1      271935            1979505
56       57      4            -1      100415            2079920
57       58      4             1       58479            2138399
58       59      4             1       24001            2162400
59       60      4             1        3680            2166080
60       61      4             1       12640            2178720
61       62      4             1       35489            2214209

[62 rows x 5 columns]